parameters:
  rounds: 5
  roundTime: 6000
  giveFood: 16
block-list:
  - ACACIA_FENCE
  - ACACIA_FENCE_GATE
  - ACACIA_LEAVES
  - ACACIA_LOG
  - ACACIA_PLANKS
  - ACACIA_SLAB
  - ACACIA_STAIRS
  - ACACIA_WOOD
  - ANDESITE
  - ANDESITE_SLAB
  - ANDESITE_STAIRS
  - ANDESITE_WALL
  - ANVIL
  - BARREL
  - BEDROCK
  - BEE_NEST
  - BELL
  - BIRCH_FENCE
  - BIRCH_FENCE_GATE
  - BIRCH_LEAVES
  - BIRCH_LOG
  - BIRCH_PLANKS
  - BIRCH_SIGN
  - BIRCH_SLAB
  - BIRCH_STAIRS
  - BIRCH_WOOD
  - BLACK_BED
  - BLACK_CONCRETE
  - BLACK_CONCRETE_POWDER
  - BLACK_GLAZED_TERRACOTTA
  - BLACK_STAINED_GLASS
  - BLACK_TERRACOTTA
  - BLACK_WOOL
  - BLAST_FURNACE
  - BLUE_BED
  - BLUE_CONCRETE
  - BLUE_CONCRETE_POWDER
  - BLUE_GLAZED_TERRACOTTA
  - BLUE_ICE
  - BLUE_STAINED_GLASS
  - BLUE_TERRACOTTA
  - BLUE_WOOL
  - BONE_BLOCK
  - BOOKSHELF
  - BRAIN_CORAL_BLOCK
  - BREWING_STAND
  - BRICK_SLAB
  - BRICK_STAIRS
  - BRICK_WALL
  - BROWN_BED
  - BROWN_CONCRETE
  - BROWN_CONCRETE_POWDER
  - BROWN_GLAZED_TERRACOTTA
  - BROWN_MUSHROOM_BLOCK
  - BROWN_STAINED_GLASS
  - BROWN_TERRACOTTA
  - BROWN_WOOL
  - CACTUS
  - CAMPFIRE
  - CARTOGRAPHY_TABLE
  - CARVED_PUMPKIN
  - CAULDRON
  - CHEST
  - CHISELED_SANDSTONE
  - CHISELED_STONE_BRICKS
  - COAL_BLOCK
  - COARSE_DIRT
  - COBBLESTONE
  - COBBLESTONE_SLAB
  - COBBLESTONE_STAIRS
  - COBBLESTONE_WALL
  - COMPARATOR
  - COMPOSTER
  - CRAFTING_TABLE
  - CUT_SANDSTONE
  - CUT_SANDSTONE_SLAB
  - CYAN_CONCRETE
  - CYAN_CONCRETE_POWDER
  - CYAN_GLAZED_TERRACOTTA
  - CYAN_STAINED_GLASS
  - CYAN_TERRACOTTA
  - CYAN_WOOL
  - DARK_OAK_FENCE
  - DARK_OAK_FENCE_GATE
  - DARK_OAK_LEAVES
  - DARK_OAK_LOG
  - DARK_OAK_PLANKS
  - DARK_OAK_SIGN
  - DARK_OAK_SLAB
  - DARK_OAK_STAIRS
  - DARK_OAK_WOOD
  - DIAMOND_ORE
  - DIORITE
  - DIORITE_STAIRS
  - DIORITE_WALL
  - DIRT
  - DISPENSER
  - DROPPER
  - EMERALD_ORE
  - ENCHANTING_TABLE
  - FARMLAND
  - FLETCHING_TABLE
  - FLOWER_POT
  - FURNACE
  - FURNACE_MINECART
  - GLASS
  - GOLD_ORE
  - GRANITE
  - GRANITE_SLAB
  - GRANITE_STAIRS
  - GRANITE_WALL
  - GRASS
  - GRASS_BLOCK
  - GRASS_PATH
  - GRAVEL
  - GRAY_BED
  - GRAY_CONCRETE
  - GRAY_CONCRETE_POWDER
  - GRAY_GLAZED_TERRACOTTA
  - GRAY_STAINED_GLASS
  - GRAY_TERRACOTTA
  - GRAY_WOOL
  - GREEN_BED
  - GREEN_CONCRETE
  - GREEN_CONCRETE_POWDER
  - GREEN_GLAZED_TERRACOTTA
  - GREEN_STAINED_GLASS
  - GREEN_TERRACOTTA
  - GREEN_WOOL
  - GRINDSTONE
  - HAY_BLOCK
  - HOPPER
  - ICE
  - INFESTED_CHISELED_STONE_BRICKS
  - INFESTED_COBBLESTONE
  - INFESTED_CRACKED_STONE_BRICKS
  - INFESTED_MOSSY_STONE_BRICKS
  - INFESTED_STONE
  - INFESTED_STONE_BRICKS
  - IRON_BARS
  - IRON_BLOCK
  - IRON_ORE
  - JUKEBOX
  - JUNGLE_FENCE
  - JUNGLE_FENCE_GATE
  - JUNGLE_LEAVES
  - JUNGLE_LOG
  - JUNGLE_PLANKS
  - JUNGLE_SIGN
  - JUNGLE_SLAB
  - JUNGLE_STAIRS
  - JUNGLE_WOOD
  - LANTERN
  - LAPIS_ORE
  - LECTERN
  - LIGHT_BLUE_BED
  - LIGHT_BLUE_CONCRETE
  - LIGHT_BLUE_CONCRETE_POWDER
  - LIGHT_BLUE_GLAZED_TERRACOTTA
  - LIGHT_BLUE_STAINED_GLASS
  - LIGHT_BLUE_TERRACOTTA
  - LIGHT_BLUE_WOOL
  - LIGHT_GRAY_BED
  - LIGHT_GRAY_CONCRETE
  - LIGHT_GRAY_CONCRETE_POWDER
  - LIGHT_GRAY_GLAZED_TERRACOTTA
  - LIGHT_GRAY_STAINED_GLASS
  - LIGHT_GRAY_TERRACOTTA
  - LIGHT_GRAY_WOOL
  - LIME_BED
  - LIME_CONCRETE
  - LIME_CONCRETE_POWDER
  - LIME_GLAZED_TERRACOTTA
  - LIME_STAINED_GLASS
  - LIME_TERRACOTTA
  - LIME_WOOL
  - LOOM
  - MAGENTA_BED
  - MAGENTA_CONCRETE
  - MAGENTA_CONCRETE_POWDER
  - MAGENTA_GLAZED_TERRACOTTA
  - MAGENTA_STAINED_GLASS
  - MAGENTA_TERRACOTTA
  - MAGENTA_WOOL
  - MAGMA_BLOCK
  - MELON
  - MOSSY_COBBLESTONE_SLAB
  - MOSSY_COBBLESTONE_STAIRS
  - MOSSY_COBBLESTONE_WALL
  - MOSSY_STONE_BRICK_SLAB
  - MOSSY_STONE_BRICK_STAIRS
  - MOSSY_STONE_BRICK_WALL
  - MOSSY_STONE_BRICKS
  - NETHERRACK
  - NOTE_BLOCK
  - OAK_FENCE
  - OAK_FENCE_GATE
  - OAK_LEAVES
  - OAK_LOG
  - OAK_PLANKS
  - OAK_SIGN
  - OAK_STAIRS
  - OAK_WOOD
  - OBSERVER
  - OBSIDIAN
  - ORANGE_BED
  - ORANGE_CONCRETE
  - ORANGE_CONCRETE_POWDER
  - ORANGE_GLAZED_TERRACOTTA
  - ORANGE_STAINED_GLASS
  - ORANGE_TERRACOTTA
  - ORANGE_WOOL
  - PACKED_ICE
  - PINK_BED
  - PINK_CONCRETE
  - PINK_CONCRETE_POWDER
  - PINK_GLAZED_TERRACOTTA
  - PINK_STAINED_GLASS
  - PINK_TERRACOTTA
  - PINK_WOOL
  - PISTON
  - POLISHED_ANDESITE
  - POLISHED_ANDESITE_SLAB
  - POLISHED_ANDESITE_STAIRS
  - POLISHED_DIORITE
  - POLISHED_DIORITE_SLAB
  - POLISHED_DIORITE_STAIRS
  - POLISHED_GRANITE
  - POLISHED_GRANITE_SLAB
  - POLISHED_GRANITE_STAIRS
  - PUMPKIN
  - PURPLE_BED
  - PURPLE_CONCRETE
  - PURPLE_CONCRETE_POWDER
  - PURPLE_GLAZED_TERRACOTTA
  - PURPLE_STAINED_GLASS
  - PURPLE_TERRACOTTA
  - PURPLE_WOOL
  - RED_BED
  - RED_CONCRETE
  - RED_CONCRETE_POWDER
  - RED_GLAZED_TERRACOTTA
  - RED_STAINED_GLASS
  - RED_TERRACOTTA
  - RED_WOOL
  - RED_MUSHROOM_BLOCK
  - REDSTONE_BLOCK
  - REDSTONE_ORE
  - REPEATER
  - SAND
  - SANDSTONE
  - SANDSTONE_SLAB
  - SANDSTONE_STAIRS
  - SANDSTONE_WALL
  - SMITHING_TABLE
  - SMOKER
  - SMOOTH_SANDSTONE
  - SMOOTH_SANDSTONE_SLAB
  - SMOOTH_SANDSTONE_STAIRS
  - SMOOTH_STONE
  - SMOOTH_STONE_SLAB
  - SNOW_BLOCK
  - SPRUCE_FENCE
  - SPRUCE_FENCE_GATE
  - SPRUCE_LEAVES
  - SPRUCE_LOG
  - SPRUCE_PLANKS
  - SPRUCE_SIGN
  - SPRUCE_SLAB
  - SPRUCE_STAIRS
  - SPRUCE_WOOD
  - STONE
  - STONE_SLAB
  - STONE_STAIRS
  - STONECUTTER
  - STRIPPED_ACACIA_LOG
  - STRIPPED_ACACIA_WOOD
  - STRIPPED_BIRCH_LOG
  - STRIPPED_BIRCH_WOOD
  - STRIPPED_DARK_OAK_LOG
  - STRIPPED_DARK_OAK_WOOD
  - STRIPPED_JUNGLE_LOG
  - STRIPPED_JUNGLE_WOOD
  - STRIPPED_OAK_LOG
  - STRIPPED_OAK_WOOD
  - STRIPPED_SPRUCE_LOG
  - STRIPPED_SPRUCE_WOOD
  - TERRACOTTA
  - TNT
  - TRAPPED_CHEST
  - WATER
  - WHITE_BED
  - WHITE_CONCRETE
  - WHITE_CONCRETE_POWDER
  - WHITE_GLAZED_TERRACOTTA
  - WHITE_STAINED_GLASS
  - WHITE_TERRACOTTA
  - WHITE_WOOL
  - YELLOW_BED
  - YELLOW_CONCRETE
  - YELLOW_CONCRETE_POWDER
  - YELLOW_GLAZED_TERRACOTTA
  - YELLOW_STAINED_GLASS
  - YELLOW_TERRACOTTA
  - YELLOW_WOOL
  